// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using genscoSQLProject1.Data;

#nullable disable

namespace genscoSQLProject1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250310213639_commentUpgrade")]
    partial class commentUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("genscoSQLProject1.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchInspectionId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchNumber")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchInspectionId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchNumber")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.BranchInspection", b =>
                {
                    b.Property<int>("BranchInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchInspectionId"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastMaintained")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevisedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchInspectionId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("BranchInspections");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.ChecklistItem", b =>
                {
                    b.Property<int>("ChecklistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool?>("DateCartridgeNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("DotInspectionDateNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("FireAlarmDateTestedNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCheckedNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("LoadCapacityNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NotApplicableNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("SafetyLastMeetingDateNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("SecurityAlarmDateTestedNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("SprinklerSystemDateTestedNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("StatePosterDatePostedNeeded")
                        .HasColumnType("bit");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.FormChecklistItems", b =>
                {
                    b.Property<int>("FormChecklistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormChecklistItemId"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("BranchInspectionId")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCartridgeInstalled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DotInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FireAlarmDateTested")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("LoadCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NotApplicable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SafetyLastMeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecurityAlarmDateTested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SprinklerSystemDateTested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatePosterDatePosted")
                        .HasColumnType("datetime2");

                    b.HasKey("FormChecklistItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("BranchInspectionId");

                    b.HasIndex("ChecklistItemId");

                    b.ToTable("FormChecklistItems");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.FormComment", b =>
                {
                    b.Property<int>("FormCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormCommentId"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("BranchInspectionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormCommentId");

                    b.HasIndex("AssetId");

                    b.HasIndex("BranchInspectionId");

                    b.HasIndex("CategoryId");

                    b.ToTable("FormComments");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.FormNote", b =>
                {
                    b.Property<int>("FormNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormNoteId"));

                    b.Property<int>("BranchInspectionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("SectionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("generalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormNoteId");

                    b.HasIndex("BranchInspectionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("FormNotes");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastMaintained")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Delete_Flag")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActiveInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Contact_id")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Default_branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Default_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Asset", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Branch", "Branch")
                        .WithMany("Assets")
                        .HasForeignKey("BranchId");

                    b.HasOne("genscoSQLProject1.Models.BranchInspection", null)
                        .WithMany("Assets")
                        .HasForeignKey("BranchInspectionId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.BranchInspection", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Branch", "Branch")
                        .WithMany("BranchInspections")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("genscoSQLProject1.Models.User", "CreatedByUser")
                        .WithMany("BranchInspections")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.ChecklistItem", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Category", "Category")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.FormChecklistItems", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("genscoSQLProject1.Models.BranchInspection", "BranchInspection")
                        .WithMany("FormChecklistItems")
                        .HasForeignKey("BranchInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("genscoSQLProject1.Models.ChecklistItem", "ChecklistItem")
                        .WithMany("FormChecklistItems")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("BranchInspection");

                    b.Navigation("ChecklistItem");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.FormComment", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("genscoSQLProject1.Models.BranchInspection", "BranchInspection")
                        .WithMany("FormComments")
                        .HasForeignKey("BranchInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("genscoSQLProject1.Models.Category", "Category")
                        .WithMany("FormComments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("BranchInspection");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.FormNote", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.BranchInspection", "BranchInspection")
                        .WithMany("FormNotes")
                        .HasForeignKey("BranchInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("genscoSQLProject1.Models.Category", "Category")
                        .WithMany("FormNotes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("genscoSQLProject1.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchInspection");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.RoleModel", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.User", "CreatedByUser")
                        .WithMany("CreatedRoles")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.User", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.RoleModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Branch", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("BranchInspections");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.BranchInspection", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("FormChecklistItems");

                    b.Navigation("FormComments");

                    b.Navigation("FormNotes");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Category", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("FormComments");

                    b.Navigation("FormNotes");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.ChecklistItem", b =>
                {
                    b.Navigation("FormChecklistItems");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.RoleModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.User", b =>
                {
                    b.Navigation("BranchInspections");

                    b.Navigation("CreatedRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
