// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using genscoSQLProject1.Data;

#nullable disable

namespace genscoSQLProject1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("genscoSQLProject1.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchInspectionId")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchInspectionId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchNumber")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.BranchInspection", b =>
                {
                    b.Property<int>("BranchInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchInspectionId"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastMaintained")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevisedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchInspectionId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("BranchInspections");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int?>("BranchInspectionId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.HasIndex("BranchInspectionId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.ChecklistItem", b =>
                {
                    b.Property<int>("ChecklistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistItemId"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchInspectionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCartridgeInstalled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DotInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FireAlarmDateTested")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("LoadCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NotApplicable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SafetyLastMeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecurityAlarmDateTested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SprinklerSystemDateTested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatePosterDatePosted")
                        .HasColumnType("datetime2");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("BranchInspectionId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastMaintained")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActiveInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Asset", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Branch", "Branch")
                        .WithMany("Assets")
                        .HasForeignKey("BranchId");

                    b.HasOne("genscoSQLProject1.Models.BranchInspection", null)
                        .WithMany("Assets")
                        .HasForeignKey("BranchInspectionId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.BranchInspection", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Branch", "Branch")
                        .WithMany("BranchInspections")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("genscoSQLProject1.Models.User", "CreatedByUser")
                        .WithMany("BranchInspections")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Category", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.BranchInspection", "BranchInspection")
                        .WithMany("Categories")
                        .HasForeignKey("BranchInspectionId");

                    b.Navigation("BranchInspection");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.ChecklistItem", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Asset", "Assets")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("genscoSQLProject1.Models.BranchInspection", "BranchInspection")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("BranchInspectionId");

                    b.HasOne("genscoSQLProject1.Models.Category", "Category")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assets");

                    b.Navigation("BranchInspection");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Role", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.User", "CreatedByUser")
                        .WithMany("CreatedRoles")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.User", b =>
                {
                    b.HasOne("genscoSQLProject1.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Branch", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("BranchInspections");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.BranchInspection", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Categories");

                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Category", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("genscoSQLProject1.Models.User", b =>
                {
                    b.Navigation("BranchInspections");

                    b.Navigation("CreatedRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
